theme = "dracula_at_night"

[editor]
mouse = false
auto-pairs = false
path-completion = false
auto-format = false
bufferline = "multiple"

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.statusline]
left = [
  "mode",
  "spinner",
  "file-name",
  "file-modification-indicator",
]
center = [
  "primary-selection-length",
  "selections",
]
right = [
  "position",
  "total-line-numbers",
  "position-percentage",
  "file-type",
  "file-encoding",
]

[editor.file-picker]
git-ignore = false
git-global = false
git-exclude = false

[editor.search]
smart-case = false

[editor.whitespace]
render = "all"
# space = "all"
# newline = true

[editor.whitespace.characters]
space = " "
nbsp = "☺"
newline = "§"
tab = "ᐅ"
tabpad = "ᐊ"

# " List of oels:ᚋ⨕
# " List of tabs:ᐅᐊ᚛→←᚜
# "tabs: 	  	 		eol
# "nbsp: .
# "trail:     
# "white:      	 
# " set listchars=eol:§,tab:<->,trail:~,nbsp:#

[editor.smart-tab]
enable = false

[keys.normal]
0 = "goto_line_start"
g = { h = "goto_first_nonwhitespace", s = "goto_line_start" }
G = "goto_last_line"
z = { g = "align_view_top" }

# Search
"*" = "search_selection"
"A-*" = "search_selection_detect_word_boundaries"

# Windows
"A-q" = "wclose"

"A-h" = "jump_view_left"
"A-j" = "jump_view_down"
"A-k" = "jump_view_up"
"A-l" = "jump_view_right"

"A-H" = "swap_view_left"
"A-J" = "swap_view_down"
"A-K" = "swap_view_up"
"A-L" = "swap_view_right"

[keys.insert]
j = { k = "normal_mode" }
k = { j = "normal_mode" }

[keys.select]
0 = "goto_line_start"
g = { h = "goto_first_nonwhitespace", s = "goto_line_start" }
G = "goto_last_line"
