theme = "dracula_at_night"

[editor]
mouse = false

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.auto-pairs]

[editor.search]
smart-case = false

[keys.normal]
0 = "goto_line_start"
g = { h = "goto_first_nonwhitespace", s = "goto_line_start" }
G = "goto_last_line"

# Windows
"A-q" = "wclose"

"A-h" = "jump_view_left"
"A-j" = "jump_view_down"
"A-k" = "jump_view_up"
"A-l" = "jump_view_right"

"A-H" = "swap_view_left"
"A-J" = "swap_view_down"
"A-K" = "swap_view_up"
"A-L" = "swap_view_right"

[keys.insert]
j = { k = "normal_mode" }
k = { j = "normal_mode" }
