[[language]]
name = "toml"

[[language]]
name = "c"
indent = { tab-width = 4, unit = "    " }

[[language]]
name = "haskell"
indent = { tab-width = 4, unit = "    " }

[[language]]
name = "latex"
indent = { tab-width = 4, unit = "    " }

[[language]]
name = "j"
scope = "source.j"
file-types = [ "ijs" ]
shebangs = [ "jconsole" ]
roots = []
comment-token = "NB."
indent = { tab-width = 2, unit = "  " }

[[language]]
name = "uiua"
scope = "source.uiua"
file-types = [ "ua" ]
roots = []
comment-token = "#"
indent = { tab-width = 2, unit = "  " }

[[language]]
name = "steight"
scope = "source.steight"
file-types = [ "sth" ]
roots = []
comment-token = "//"
indent = { tab-width = 4, unit = "    " }

[auto-pairs]
